### ISSUE TITLE
 not enough values to unpack 

### ISSUE THREAD

**Issue by yezhiwei** [driving-behavior/DBNet#21]
Traceback (most recent call last):
  File "C:/Users/叶志伟/PycharmProjects/untitled/DBNet-master/predict.py", line 140, in <module>
    predict()
  File "C:/Users/叶志伟/PycharmProjects/untitled/DBNet-master/predict.py", line 56, in predict
    data_input = provider.Provider()
  File "C:\Users\叶志伟\PycharmProjects\untitled\DBNet-master\provider.py", line 34, in __init__
    self.read()
  File "C:\Users\叶志伟\PycharmProjects\untitled\DBNet-master\provider.py", line 66, in read
    self.read_from(train_sub, filename, "train")
  File "C:\Users\叶志伟\PycharmProjects\untitled\DBNet-master\provider.py", line 106, in read_from
    self.X_train1, self.X_train2, self.Y_train1, self.Y_train2 = zip(*c)
ValueError: not enough values to unpack (expected 4, got 0)

**Comment by BLOSSOM1994** [comment]
Hello
You need to change the data path in provider.py based on your system
